on: push
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@master
    - name: fetch JWT token from CxSAST
    #  uses: wei/curl@v1
      run: |
        IP=$(curl --request POST 'https://fc20-150-129-159-196.ngrok.io/cxrestapi/auth/identity/connect/token' \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode 'username=Admin@cx' \
        --data-urlencode 'password=Admin@123' \
        --data-urlencode 'grant_type=password' \
        --data-urlencode 'scope=access_control_api' \
        --data-urlencode 'client_id=resource_owner_client' \
        --data-urlencode 'client_secret=014DF517-39D1-4453-B7B3-9930C563627C')
        ACCESS_TOKEN=$(echo $IP | grep -Eo '"access_token"[^,]*' | grep -Eo '[^:]*$' | sed -e 's/^"//' -e 's/"$//')
        curl --location --request POST 'https://fc20-150-129-159-196.ngrok.io/cxrestapi/auth/teams' \
        --header "Authorization: Bearer $ACCESS_TOKEN" \
        --header 'Content-Type: application/json' \
        --data-raw '{
        "name": "Team Test ddd",
        "parentId": 1
        }'
