name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkmarx AST CLI Action
        uses: Checkmarx/ast-github-action@v0.28 #Github Action version
        with:
          project_name: KHTest_GithubAction
          cx_tenant: dp_wp_account
          base_uri: https://eu.ast.checkmarx.net 
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          branch: master
